trigger:
- master

pool:
  vmImage: 'windows-latest'

steps:
- task: UsePythonVersion@0
  inputs:
    versionSpec: '3.x'   # Usa a última versão Python 3 disponível
    addToPath: true

- script: |
    python -m pip install --upgrade pip
    pip install -r requirements.txt
  displayName: 'Instalar dependências'

- script: |
    python run_tests.py
  displayName: 'Executar testes'

- task: PublishBuildArtifacts@1
  inputs:
    PathtoPublish: 'report.html'  # caminho do relatório HTML gerado
    ArtifactName: 'TestReport'
    publishLocation: 'Container'
